/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package AccesosAuxiliares;

import AccesosPrincipales.MetodosConsultaInmuebles;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import poo.javabnb.Anfitrion;
import poo.javabnb.Inmueble;

/**
 *
 * @author crestas
 */
public class DialogCrearInmuebles extends javax.swing.JDialog {

    /**
     * Creates new form DialogCrearInmuebles
     */
    public DialogCrearInmuebles(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tituloInmueble = new javax.swing.JTextField();
        calleInmueble = new javax.swing.JTextField();
        numeroInmueble = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cpInmueble = new javax.swing.JTextField();
        ciudadInmueble = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        imagenesInmueble = new javax.swing.JButton();
        i1toi2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        i2toi3 = new javax.swing.JButton();
        i2toi1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tipoInmueble = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        maxHuespedes = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        numHabitaciones = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        numCamas = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        numBaños = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        i3toi2 = new javax.swing.JButton();
        finalizar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        precioNoche = new javax.swing.JSlider();
        jLabel17 = new javax.swing.JLabel();
        wifi = new javax.swing.JRadioButton();
        aireAcondicionado = new javax.swing.JRadioButton();
        cocina = new javax.swing.JRadioButton();
        calefaccion = new javax.swing.JRadioButton();
        lavadora = new javax.swing.JRadioButton();
        aparcamiento = new javax.swing.JRadioButton();
        piscina = new javax.swing.JRadioButton();
        zonaTrabajo = new javax.swing.JRadioButton();
        labelPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(550, 450));
        jPanel1.setMinimumSize(new java.awt.Dimension(550, 450));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 450));
        jPanel1.setSize(new java.awt.Dimension(550, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NUEVO INMUEBLE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 62, -1, -1));

        jLabel2.setText("Título");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 123, -1, -1));

        tituloInmueble.setText("tituloInmueble");
        tituloInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloInmuebleActionPerformed(evt);
            }
        });
        jPanel1.add(tituloInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 146, -1, -1));

        calleInmueble.setText("jTextField3");
        jPanel1.add(calleInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 210, -1, -1));

        numeroInmueble.setText("jTextField4");
        jPanel1.add(numeroInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        jLabel4.setText("Numero");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 187, -1, -1));

        jLabel3.setText("Calle");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 187, -1, -1));

        jLabel5.setText("C.P.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 251, -1, -1));

        cpInmueble.setText("cpInmueble");
        jPanel1.add(cpInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 274, -1, -1));

        ciudadInmueble.setText("jTextField5");
        ciudadInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadInmuebleActionPerformed(evt);
            }
        });
        jPanel1.add(ciudadInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 274, -1, -1));

        jLabel6.setText("Ciudad");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 251, -1, -1));

        jLabel7.setText("Introduzca imagenes del inmueble");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 323, -1, -1));

        imagenesInmueble.setText("Examinar archivos locales");
        imagenesInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenesInmuebleActionPerformed(evt);
            }
        });
        jPanel1.add(imagenesInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 346, 190, -1));

        i1toi2.setText("Siguiente");
        i1toi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i1toi2ActionPerformed(evt);
            }
        });
        jPanel1.add(i1toi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));

        jTabbedPane1.addTab("tab1", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("NUEVO INMUEBLE");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 62, -1, -1));

        i2toi3.setText("Siguiente");
        i2toi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i2toi3ActionPerformed(evt);
            }
        });
        jPanel2.add(i2toi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));

        i2toi1.setText("Atrás");
        i2toi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i2toi1ActionPerformed(evt);
            }
        });
        jPanel2.add(i2toi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel9.setText("Tipo de Propiedad");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 118, -1, -1));

        tipoInmueble.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa ", "Apartamento", " " }));
        jPanel2.add(tipoInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 141, -1, -1));

        jLabel10.setText("Máximo de huespedes");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 194, -1, -1));

        maxHuespedes.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        maxHuespedes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        maxHuespedes.setValue(1);
        maxHuespedes.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                maxHuespedesAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(maxHuespedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 217, -1, -1));

        jLabel11.setText("Número de habitaciones");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 194, -1, -1));

        numHabitaciones.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        numHabitaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        numHabitaciones.setValue(1);
        numHabitaciones.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                numHabitacionesAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(numHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 217, -1, -1));

        jLabel12.setText("Número de camas");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 258, -1, -1));

        numCamas.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        numCamas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        numCamas.setValue(1);
        numCamas.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                numCamasAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(numCamas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 281, -1, -1));

        jLabel13.setText("Número de baños");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 258, -1, -1));

        numBaños.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        numBaños.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        numBaños.setValue(1);
        numBaños.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                numBañosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(numBaños, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 281, -1, -1));

        jTabbedPane1.addTab("tab2", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("NUEVO INMUEBLE");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 62, -1, -1));

        i3toi2.setText("Atrás");
        i3toi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i3toi2ActionPerformed(evt);
            }
        });
        jPanel3.add(i3toi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        finalizar.setText("Finalizar");
        finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarActionPerformed(evt);
            }
        });
        jPanel3.add(finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));

        jLabel15.setText("Precio por noche");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 118, -1, -1));

        precioNoche.setMajorTickSpacing(1);
        precioNoche.setMaximum(1000);
        precioNoche.setMinimum(1);
        precioNoche.setMinorTickSpacing(1);
        precioNoche.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        precioNoche.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                precioNocheAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        precioNoche.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                precioNocheStateChanged(evt);
            }
        });
        jPanel3.add(precioNoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel17.setText("Servicios");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 173, -1, -1));

        wifi.setText("Wifi");
        jPanel3.add(wifi, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 199, -1, -1));

        aireAcondicionado.setText("Aire Acondicionado");
        jPanel3.add(aireAcondicionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 226, -1, -1));

        cocina.setText("Cocina");
        jPanel3.add(cocina, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 280, -1, -1));

        calefaccion.setText("Calefacción");
        jPanel3.add(calefaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 253, -1, -1));

        lavadora.setText("Lavadora");
        jPanel3.add(lavadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 199, -1, -1));

        aparcamiento.setText("Aparcamiento");
        jPanel3.add(aparcamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 226, -1, -1));

        piscina.setText("Piscina");
        jPanel3.add(piscina, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 253, -1, -1));

        zonaTrabajo.setText("Zona de trabajo");
        jPanel3.add(zonaTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 280, -1, -1));

        labelPrice.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(labelPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 50, 20));

        jTabbedPane1.addTab("tab3", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 550, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tituloInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloInmuebleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloInmuebleActionPerformed

    private void ciudadInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadInmuebleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadInmuebleActionPerformed
    private String paths = "";
    private File[] files;
    private int result;

    private void imagenesInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenesInmuebleActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(true); // Permite seleccionar múltiples archivos
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY); // Solo archivos, no directorios
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image files", "jpg", "png", "gif", "bmp")); // Filtra solo archivos de imagen

        result = fileChooser.showOpenDialog(null); // Muestra el diálogo del selector de archivos

        if (result == JFileChooser.APPROVE_OPTION) {
            files = fileChooser.getSelectedFiles(); // Obtiene los archivos seleccionados
     
            for (int i = 0; i < files.length; i++) {
                paths += files[i].getName();
                // Añadir ";" después de cada elemento excepto el último
                if (i < files.length - 1) {
                    paths += ",";
                }
            }
        } else if (result == JFileChooser.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(null, "No se encontró ningún archivo");
        }
    }//GEN-LAST:event_imagenesInmuebleActionPerformed

    private void i1toi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i1toi2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_i1toi2ActionPerformed

    private void i2toi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i2toi3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);

    }//GEN-LAST:event_i2toi3ActionPerformed

    private void i2toi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i2toi1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);

    }//GEN-LAST:event_i2toi1ActionPerformed

    private void maxHuespedesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_maxHuespedesAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_maxHuespedesAncestorAdded

    private void numHabitacionesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_numHabitacionesAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_numHabitacionesAncestorAdded

    private void numCamasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_numCamasAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_numCamasAncestorAdded

    private void numBañosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_numBañosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_numBañosAncestorAdded

    private void i3toi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i3toi2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_i3toi2ActionPerformed

    private void precioNocheAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_precioNocheAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_precioNocheAncestorAdded

    private void precioNocheStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_precioNocheStateChanged
        // TODO add your handling code here:
        int price = precioNoche.getValue();
        labelPrice.setText(String.valueOf(price));
    }//GEN-LAST:event_precioNocheStateChanged
    private void finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarActionPerformed
        // TODO add your handling code here:
        try (FileWriter writer = new FileWriter("image_paths.txt", true)) { // Crea o abre el archivo para añadir texto al final
            writer.write(tituloInmueble.getText().trim() + "," + paths.trim() + "\n"); // Escribe todas las rutas en una sola línea en el archivo de texto
            System.out.println(paths.trim());
            JOptionPane.showMessageDialog(null, "Inmueble creado correctamente");
            
            if (result == JFileChooser.APPROVE_OPTION) {
                MetodosConsultaInmuebles.saveImages(files);
            } else {
                System.out.println("No se seleccionaron archivos.");
            }

        } catch (IOException e) {
            System.out.println("Ha ocurrido un error al escribir en el archivo");
            e.printStackTrace();
        }
        
        dispose();
    }//GEN-LAST:event_finalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogCrearInmuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogCrearInmuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogCrearInmuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogCrearInmuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogCrearInmuebles dialog = new DialogCrearInmuebles(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aireAcondicionado;
    private javax.swing.JRadioButton aparcamiento;
    private javax.swing.JRadioButton calefaccion;
    private javax.swing.JTextField calleInmueble;
    private javax.swing.JTextField ciudadInmueble;
    private javax.swing.JRadioButton cocina;
    private javax.swing.JTextField cpInmueble;
    private javax.swing.JButton finalizar;
    private javax.swing.JButton i1toi2;
    private javax.swing.JButton i2toi1;
    private javax.swing.JButton i2toi3;
    private javax.swing.JButton i3toi2;
    private javax.swing.JButton imagenesInmueble;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelPrice;
    private javax.swing.JRadioButton lavadora;
    private javax.swing.JSpinner maxHuespedes;
    private javax.swing.JSpinner numBaños;
    private javax.swing.JSpinner numCamas;
    private javax.swing.JSpinner numHabitaciones;
    private javax.swing.JTextField numeroInmueble;
    private javax.swing.JRadioButton piscina;
    private javax.swing.JSlider precioNoche;
    private javax.swing.JComboBox<String> tipoInmueble;
    private javax.swing.JTextField tituloInmueble;
    private javax.swing.JRadioButton wifi;
    private javax.swing.JRadioButton zonaTrabajo;
    // End of variables declaration//GEN-END:variables
}
