/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package AccesosAuxiliares;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import poo.javabnb.Anfitrion;
import poo.javabnb.Inmueble;

/**
 *
 * @author crestas
 */
public class DialogCrearInmuebles extends javax.swing.JDialog {

    /**
     * Creates new form DialogCrearInmuebles
     */
    public DialogCrearInmuebles(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tituloInmueble = new javax.swing.JTextField();
        calleInmueble = new javax.swing.JTextField();
        numeroInmueble = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cpInmueble = new javax.swing.JTextField();
        ciudadInmueble = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        imagenesInmueble = new javax.swing.JButton();
        i1toi2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        i2toi3 = new javax.swing.JButton();
        i2toi1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tipoInmueble = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        i3toi2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        sliderPrice = new javax.swing.JSlider();
        jLabel17 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        labelPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(550, 450));
        jPanel1.setMinimumSize(new java.awt.Dimension(550, 450));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 450));
        jPanel1.setSize(new java.awt.Dimension(550, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NUEVO INMUEBLE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 62, -1, -1));

        jLabel2.setText("Título");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 123, -1, -1));

        tituloInmueble.setText("tituloInmueble");
        tituloInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloInmuebleActionPerformed(evt);
            }
        });
        jPanel1.add(tituloInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 146, -1, -1));

        calleInmueble.setText("jTextField3");
        jPanel1.add(calleInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 210, -1, -1));

        numeroInmueble.setText("jTextField4");
        jPanel1.add(numeroInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        jLabel4.setText("Numero");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 187, -1, -1));

        jLabel3.setText("Calle");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 187, -1, -1));

        jLabel5.setText("C.P.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 251, -1, -1));

        cpInmueble.setText("cpInmueble");
        jPanel1.add(cpInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 274, -1, -1));

        ciudadInmueble.setText("jTextField5");
        ciudadInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadInmuebleActionPerformed(evt);
            }
        });
        jPanel1.add(ciudadInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 274, -1, -1));

        jLabel6.setText("Ciudad");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 251, -1, -1));

        jLabel7.setText("Introduzca imagenes del inmueble");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 323, -1, -1));

        imagenesInmueble.setText("Examinar archivos locales");
        imagenesInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenesInmuebleActionPerformed(evt);
            }
        });
        jPanel1.add(imagenesInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 346, 190, -1));

        i1toi2.setText("Siguiente");
        i1toi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i1toi2ActionPerformed(evt);
            }
        });
        jPanel1.add(i1toi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));

        jTabbedPane1.addTab("tab1", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("NUEVO INMUEBLE");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 62, -1, -1));

        i2toi3.setText("Siguiente");
        i2toi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i2toi3ActionPerformed(evt);
            }
        });
        jPanel2.add(i2toi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));

        i2toi1.setText("Atrás");
        i2toi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i2toi1ActionPerformed(evt);
            }
        });
        jPanel2.add(i2toi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel9.setText("Tipo de Propiedad");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 118, -1, -1));

        tipoInmueble.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa ", "Apartamento", " " }));
        jPanel2.add(tipoInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 141, -1, -1));

        jLabel10.setText("Máximo de huespedes");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 194, -1, -1));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinner1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSpinner1.setValue(1);
        jSpinner1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jSpinner1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 217, -1, -1));

        jLabel11.setText("Número de habitaciones");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 194, -1, -1));

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinner2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSpinner2.setValue(1);
        jSpinner2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jSpinner2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 217, -1, -1));

        jLabel12.setText("Número de camas");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 258, -1, -1));

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinner3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSpinner3.setValue(1);
        jSpinner3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jSpinner3AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 281, -1, -1));

        jLabel13.setText("Número de baños");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 258, -1, -1));

        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinner4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSpinner4.setValue(1);
        jSpinner4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jSpinner4AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 281, -1, -1));

        jTabbedPane1.addTab("tab2", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("NUEVO INMUEBLE");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 62, -1, -1));

        i3toi2.setText("Atrás");
        i3toi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i3toi2ActionPerformed(evt);
            }
        });
        jPanel3.add(i3toi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jButton2.setText("Finalizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));

        jLabel15.setText("Precio por noche");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 118, -1, -1));

        sliderPrice.setMajorTickSpacing(1);
        sliderPrice.setMaximum(1000);
        sliderPrice.setMinimum(1);
        sliderPrice.setMinorTickSpacing(1);
        sliderPrice.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sliderPrice.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                sliderPriceAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        sliderPrice.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderPriceStateChanged(evt);
            }
        });
        jPanel3.add(sliderPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel17.setText("Servicios");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 173, -1, -1));

        jRadioButton1.setText("Wifi");
        jPanel3.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 199, -1, -1));

        jRadioButton2.setText("Aire Acondicionado");
        jPanel3.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 226, -1, -1));

        jRadioButton3.setText("Cocina");
        jPanel3.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 280, -1, -1));

        jRadioButton4.setText("Calefacción");
        jPanel3.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 253, -1, -1));

        jRadioButton5.setText("Lavadora");
        jPanel3.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 199, -1, -1));

        jRadioButton6.setText("Aparcamiento");
        jPanel3.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 226, -1, -1));

        jRadioButton7.setText("Piscina");
        jPanel3.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 253, -1, -1));

        jRadioButton8.setText("Zona de trabajo");
        jPanel3.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 280, -1, -1));

        labelPrice.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(labelPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 50, 20));

        jTabbedPane1.addTab("tab3", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 550, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tituloInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloInmuebleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloInmuebleActionPerformed

    private void ciudadInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadInmuebleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadInmuebleActionPerformed
    private StringBuilder paths;
    private void imagenesInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenesInmuebleActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(true); // Permite seleccionar múltiples archivos
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY); // Solo archivos, no directorios
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image files", "jpg", "png", "gif", "bmp")); // Filtra solo archivos de imagen

        int result = fileChooser.showOpenDialog(null); // Muestra el diálogo del selector de archivos

        if (result == JFileChooser.APPROVE_OPTION) {
            File[] files = fileChooser.getSelectedFiles(); // Obtiene los archivos seleccionados
            
            //StringBuilder paths = new StringBuilder(); // Usamos StringBuilder para construir la línea de texto
            /*for (File file : files) {
                if (paths.length() > 0) {
                    paths.append(";"); // Añade una coma antes de cada archivo excepto el primero
                }
                paths.append(file.getAbsolutePath()); // Añade la ruta del archivo al StringBuilder
                System.out.println(file);
            }*/
            String paths = "";
            for (int i = 0; i < files.length; i++) {
                paths += files[i].getName();
                // Añadir ";" después de cada elemento excepto el último
                if (i < files.length - 1) {
                    paths += ";";
                }
            }
            System.out.println(paths);

            
        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("No se seleccionó ningún archivo.");
        }
    }//GEN-LAST:event_imagenesInmuebleActionPerformed

    private void i1toi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i1toi2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_i1toi2ActionPerformed

    private void i2toi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i2toi3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);

    }//GEN-LAST:event_i2toi3ActionPerformed

    private void i2toi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i2toi1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);

    }//GEN-LAST:event_i2toi1ActionPerformed

    private void jSpinner1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jSpinner1AncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_jSpinner1AncestorAdded

    private void jSpinner2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jSpinner2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner2AncestorAdded

    private void jSpinner3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jSpinner3AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner3AncestorAdded

    private void jSpinner4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jSpinner4AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner4AncestorAdded

    private void i3toi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i3toi2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_i3toi2ActionPerformed

    private void sliderPriceAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_sliderPriceAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_sliderPriceAncestorAdded

    private void sliderPriceStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderPriceStateChanged
        // TODO add your handling code here:
        int price = sliderPrice.getValue();
        labelPrice.setText(String.valueOf(price));
    }//GEN-LAST:event_sliderPriceStateChanged
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try (FileWriter writer = new FileWriter("image_paths.txt", true)) { // Crea o abre el archivo para añadir texto al final
            writer.write(/*tituloInmueble.getText().trim() + "," + */paths.toString() + "\n"); // Escribe todas las rutas en una sola línea en el archivo de texto
        } catch (IOException e) {
            System.out.println("Ha ocurrido un error al escribir en el archivo");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogCrearInmuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogCrearInmuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogCrearInmuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogCrearInmuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogCrearInmuebles dialog = new DialogCrearInmuebles(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField calleInmueble;
    private javax.swing.JTextField ciudadInmueble;
    private javax.swing.JTextField cpInmueble;
    private javax.swing.JButton i1toi2;
    private javax.swing.JButton i2toi1;
    private javax.swing.JButton i2toi3;
    private javax.swing.JButton i3toi2;
    private javax.swing.JButton imagenesInmueble;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelPrice;
    private javax.swing.JTextField numeroInmueble;
    private javax.swing.JSlider sliderPrice;
    private javax.swing.JComboBox<String> tipoInmueble;
    private javax.swing.JTextField tituloInmueble;
    // End of variables declaration//GEN-END:variables
}
