/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package AccesosPrincipales;

import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class DialogMenuParticular extends javax.swing.JDialog {

    /**
     * Creates new form DialogMenuParticular
     */
    public DialogMenuParticular(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonInmuebleDispo = new javax.swing.JButton();
        buttonMisReservas = new javax.swing.JButton();
        buttonPerfil = new javax.swing.JButton();
        buttonCerrarSesion = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelExplorarReservas = new javax.swing.JPanel();
        panelMisReservas = new javax.swing.JPanel();
        panelMiPerfil = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonInmuebleDispo.setText("Explorar Reservas");
        buttonInmuebleDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInmuebleDispoActionPerformed(evt);
            }
        });
        jPanel1.add(buttonInmuebleDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 130, -1));

        buttonMisReservas.setText("Mis Reservas");
        buttonMisReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMisReservasActionPerformed(evt);
            }
        });
        jPanel1.add(buttonMisReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 130, -1));

        buttonPerfil.setText("Mi Perfil");
        buttonPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(buttonPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 130, -1));

        buttonCerrarSesion.setText("Cerrar Sesion");
        buttonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 130, -1));

        ImageIcon d = new ImageIcon("src/main/java/com/images/logo2rec.png");
        jLabel29.setIcon(d);
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 106, 125));

        jLabel30.setBackground(new java.awt.Color(0, 0, 0));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel30.setText("JAVABNB");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 500));

        jTabbedPane1.addTab("tab1", panelExplorarReservas);
        jTabbedPane1.addTab("tab2", panelMisReservas);

        panelMiPerfil.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.addTab("tab3", panelMiPerfil);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, -40, 590, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonInmuebleDispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInmuebleDispoActionPerformed
        jTabbedPane1.setSelectedIndex(0);

    }//GEN-LAST:event_buttonInmuebleDispoActionPerformed

    private void buttonMisReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMisReservasActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_buttonMisReservasActionPerformed

    private void buttonPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPerfilActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_buttonPerfilActionPerformed

    private void buttonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCerrarSesionActionPerformed
        // TODO add your handling code here:
        dispose();
        FrameInicio inicio = new FrameInicio();
        inicio.setVisible(true);
        
    }//GEN-LAST:event_buttonCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogMenuParticular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogMenuParticular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogMenuParticular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogMenuParticular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogMenuParticular dialog = new DialogMenuParticular(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCerrarSesion;
    private javax.swing.JButton buttonInmuebleDispo;
    private javax.swing.JButton buttonMisReservas;
    private javax.swing.JButton buttonPerfil;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelExplorarReservas;
    private javax.swing.JPanel panelMiPerfil;
    private javax.swing.JPanel panelMisReservas;
    // End of variables declaration//GEN-END:variables
}
